package com.bankbabu.balance.application;


public interface Constants {

  // Permissions
  String[] WRITE_EXTERNAL_STORAGE_PERMISSIONS = {
      "android.permission.WRITE_EXTERNAL_STORAGE"
  };

  // Request results
  int RC_WRITE_EXTERNAL_STORAGE = 200;

  String KEY_LANGUAGE_DIALOG = "language_dialog";

  String EXTRA_BILL_ID_ALARM = "ID";
  String EXTRA_ALARM_ID = "alarmId";
  String EXTRA_ACCOUNT_ID = "AC_ID";
  String EXTRA_ACCOUNT_NAME = "NAME";
  String EXTRA_ACCOUNT_NUMBER = "AC_NUMBER";
  String EXTRA_BANK_NAME = "BANK_NAME";
  String EXTRA_BILL_NOTE = "BNOTE";
  String EXTRA_CONTACT = "CONTACT";
  String EXTRA_ACCOUNT_TYPE = "AC_TYPE";
  String EXTRA_OWNER_TYPE = "AC_OWNER_TYPE";
  String EXTRA_BILL_NOTIFICATION = "NOTIFICATION";
  String EXTRA_BANK_BALANCE = "BANK_BALANCE";
  String EXTRA_BANK_STATEMENT = "STATEMENT";
  String EXTRA_CUSTOMER_CARE = "CUSTOMER_CARE";
  String EXTRA_INTERNET_BANKING = "INTERNET_BANKING";
  String EXTRA_STATE_ID = "STATE_ID";
  String EXTRA_STATE_NAME = "STATE_NAME";
  String EXTRA_ACCOUNT_IFSC = "IFSC";
  String EXTRA_POST = "POST";
  String EXTRA_BILL_PAYEE = "BPAYEE";
  String EXTRA_BILL_AMOUNT = "BAMOUNT";
  String EXTRA_BILL_CATEGORY_NAME = "BCATNAME";
  String EXTRA_BILL_DUE_DATE = "BDUEDATE";
  String EXTRA_BILL_CATEGORY_ICON = "BCATICON";
  String EXTRA_BILL_TYPE = "BTYPE";
  String EXTRA_BANK_TITLE = "TITLE";
  String EXTRA_BANK_MESSAGE = "MESSAGE";
  String EXTRA_BANK_INFO = "INFO";
  String EXTRA_BANK_PHONE_NUMBER = "PHNO";
  String EXTRA_PUSH = "PUSH";
  String EXTRA_BILL_ID = "BID";
  String EXTRA_BILL_CUSTOM_DUE_DATE = "CUSTOM_DATE";
  String EXTRA_BILL_REPEAT = "BREPEAT";
  String EXTRA_BILL_NEXT_DUE_DATE = "NEXTDUEdATE";
  String EXTRA_BILL_REPEAT_EVERY = "REPET_EVARY";
  String EXTRA_BILL_REPEAT_BY = "REPET_BY";
  String EXTRA_BILL_STATUS = "STATUS";
  String EXTRA_BILL_BUTTON = "BUTTON";
  String EXTRA_ACCOUNT = "ACCOUNT";
  String EXTRA_ACCOUNT_SELECT = "ACCOUNT_SELECT";
}
